const express = require("express");
const router = express.Router();
const productRoutes = require("./product.route.js");
const transaction = require("../Routes/transaction.route.js");
console.log("router loaded");
// console.log( productRoutes);
router.use('/', require('./Authroutes.js'));
router.use('/users', require('./userRouter.js'));
router.use('/redis', require('./redisRoutes.js'));
router.use('/', require('./Twillioroutes.js'));
router.use('/', require('./Profileroutes.js'));
router.use("/api/products" ,productRoutes);
router.use('/api/chat',require('./chat.js'));
router.use("/api/transaction",transaction);
module.exports = router;
