const express = require("express");
const router = express.Router();
const productRoutes = require("./product.route.js");
const transaction = require("../Routes/transaction.route.js");
const shopRoutes = require("../Routes/shopRoutes");
const logger = require('../utils/logger');
logger.debug('router loaded');
// console.log( productRoutes);
router.use('/', require('./Authroutes.js'));
router.use('/users', require('./userRouter.js'));
router.use('/redis', require('./redisRoutes.js'));
router.use('/', require('./Twillioroutes.js'));
router.use('/', require('./Profileroutes.js'));
router.use("/api/products" ,productRoutes);
router.use('/api/chat',require('./chat.js'));
router.use("/api/transaction",transaction);
router.use('/api/payments', require('./payment-proxy.routes'));
router.use("/",require("./Followerroutes.js"));
router.use("/Orders",require("./Order.js"));
router.use("/",require("./Admin.js"));
router.use("/chatbot", require("./ChatbotRoutes.js"));
router.use("/concern", require("./concernRoutes.js"));
router.use("/reviews", require("./reviewRoutes.js"));
router.use("/api/shops", shopRoutes);
router.use("/api/ads", require("./adRoutes.js"));
router.use("/api/notifications", require("./notificationRoutes.js"));
router.use("/api/logs", require("./logRoutes.js"));
module.exports = router;
