spring:
  data:
    mongodb:
      uri: mongodb+srv://tiwariraj1202:RAJtiwari9165%40@cluster0.dwmup.mongodb.net/SetGo?retryWrites=true&w=majority&appName=Cluster0

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8085
